### ISSUE TITLE
"This tool is no longer needed"

### ISSUE THREAD

**Issue by luckman212** [hydrixos/filecoordination-dump#1]
@hydrixos as of 2023-09-27 your repo is literally the _ONLY_ search result on the entire internet for the phrase `"fileproviderctl coordinate"`

<img width="996" src="https://github.com/hydrixos/filecoordination-dump/assets/1992842/c7028359-bcb9-4c2b-b4ae-476633a95beb">

I landed here because I was trying to execute the command `fileproviderctl coordinate -e` on my macOS Sonoma 14.0 system. It just silently fails and prints out the helptext. Your tool still seems to run. Just wondering if anyone else experiences the same.

I also note they seem to have removed the `enumerate` verb from the tool as well as of 14.0.

**Comment by hydrixos** [comment]
I can confirm that `fileproviderctl coordinate -e` no longer works in Sonoma, even though it is still part of the tool's help screen. May be it's worth to file a Feedback to Apple…

I added a hint to the Readme file. Thanks for letting me know!
